@startuml

' avoid problems with angled crows feet
skinparam linetype ortho

!include Users_Transaction.puml

entity TradingPair {
    * id
    --
    * base_currency_symbol : string
    * quote_currency_symbol : string
    * pair_symbol : string
    * market_status : enum
    --
    * created_at
    * updated_at
}

entity OrderBook {
    * id
    --
    * user_id : integer
    * trading_pair_symbol : string
    * order_indicator : enum
    * order_type : enum
    * order_status : enum
    * price : decimal
    * quantity : decimal
    --
    * created_at
    * updated_at
}

entity Trades {
    * id
    --
    * user_id : integer
    * pair_symbol : string
    * buyer_id : integer
    * seller_id : integer
    * price : decimal
    * quantity : decimal
    --
    * created_at
    * updated_at
}

entity TradeHistory {
    * id
    --
    * user_id : integer
    * pair_symbol : string
    * price : decimal
    * quantity : decimal
    * trade_type : enum
    * trade_status : enum
    * trade_event : enum
    --
    * created_at
    * updated_at
}

' Relationships

User --o{ OrderBook : owner
User --o{ Trades : buyer or seller
User --o{ TradeHistory : owner
User --o{ Transaction : owner
User --o{ PendingTransaction : owner

OrderBook }o-- TradingPair : trading pair
Trades }o-- TradingPair : trading pair

Trades ||--o{ Transaction : buyer or seller
Trades ||--o{ PendingTransaction : buyer or seller

@enduml
