@startuml

entity TradingPair {
    * id
    --
    * base_currency_symbol : string
    * quote_currency_symbol : string
    * pair_symbol : string
    * market_status : enum
    --
    * created_at
    * updated_at
}

entity OrderBook {
    * id
    --
    * user_id : integer
    * trading_pair_symbol : string
    * order_indicator : enum
    * order_type : enum
    * order_status : enum
    * price : numeric
    * quantity : numeric
    --
    * created_at
    * updated_at
}

entity TradeHistory {
    * id
    --
    * user_id : integer
    * pair_symbol : string
    * buyer_id : integer
    * seller_id : integer
    * price : numeric
    * quantity : numeric
    --
    * created_at
    * updated_at
}

' Relationships

User --o{ OrderBook : owner
User --o{ TradeHistory : buyer or seller

OrderBook }o-- TradingPair : trading pair
TradeHistory }o-- TradingPair : trading pair

@enduml
