@startuml

' avoid problems with angled crows feet
skinparam linetype ortho

entity FiatCurrency {
    * id
    --
    * name : string
    * symbol : string
    --
    * created_at
    * updated_at
}

entity TradeFiat {
    * id
    --
    * user_id : integer
    * buyer_id : integer
    * seller_id : integer
    * fiat_currency_symbol : integer
    * crypto_currency_symbol : integer
    * trade_type : enum
    * trade_status : enum
    * payment_method : enum
    * payment_information : string
    * fiat_amount : decimal
    * crypto_amount : decimal
    * exchange_rate : decimal
    * buyer_wallet_address : string
    --
    * created_at
    * updated_at
}

entity FiatTransaction {
    * id : integer
    --
    * user_id : integer
    * trade_fiat_id : integer
    * currency_symbol : string
    * amount : decimal
    * type : enum
    * status : enum
    --
    * created_at
    * updated_at
}

entity PendingFiatTransaction {
    * id : integer
    --
    * user_id : integer
    * trade_fiat_id : integer
    * currency_symbol : string
    * amount : decimal
    * type : enum
    * status : enum
    --
    * created_at
    * updated_at
}

User ||--o{ TradeFiat
User ||--o{ FiatTransaction
User ||--o{ PendingFiatTransaction

TradeFiat }o--o| FiatCurrency

' TradeFiat has many FiatTransaction, but FiatTransaction has only one TradeFiat
TradeFiat ||--{ FiatTransaction

' TradeFiat has many PendingFiatTransaction, but PendingFiatTransaction has only one TradeFiat
TradeFiat ||--{ PendingFiatTransaction

@enduml
